# roles/webservers/tasks/main.yml
---

- name: Add apt signing key for nginx
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
  tags: nginx

- name: Add nginx repository into sources list
  apt_repository: repo='deb http://nginx.org/packages/ubuntu/ 
      {{ ansible_distribution_release }} nginx' state=present
  tags: nginx
      
- name: Add nginx source repository into sources list
  apt_repository: repo='deb-src http://nginx.org/packages/ubuntu/ 
      {{ ansible_distribution_release }} nginx' state=present
  tags: nginx

- name: Ensure nginx is at the latest version
  apt: name=nginx state=latest
  tags: nginx

- name: Configure nginx.conf file
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  tags: nginx
  notify: restart nginx
 
- name: Start the nginx service
  service: name=nginx state=started enabled=true
  tags: nginx
      
- name: Set ufw to allow http
  ufw: rule=allow port=http
  tags: ufw

- name: Create server files path
  file: path="/var/www/tutorial" state=directory mode=0755
  tags: tutorial

- name: Set /var/www permission
  file: path="/var/www" mode=0755
  tags: tutorial

- name: Copy the site's files
  copy: src=tutorial/ dest=/var/www/tutorial directory_mode
  tags: tutorial
