# roles/common/tasks/main.yml
---

- name: Run apt-get update if the latest one is more than an hour ago
  apt: update_cache=yes cache_valid_time=3600

- name: Ensure ufw is at the latest version
  apt: pkg=ufw state=latest
  tags: ufw

- name: Set ufw policy to deny all incoming connections
  ufw: policy=deny direction=incoming
  tags: ufw

- name: Set ufw policy to allow all ougoing connections
  ufw: policy=allow direction=outgoing
  tags: ufw

- name: Set ufw to allow ntp
  ufw: rule=allow port=ntp
  tags: ufw

- name: Set ufw rule to limit connections on ssh/tcp
  ufw: rule=limit port=ssh proto=tcp
  tags: ufw

- name: Enable ufw logging
  ufw: logging=on
  tags: ufw

- name: Start ufw
  ufw: state=enabled
  tags: ufw

- name: Ensure cron-apt is at the latest version
  apt: pkg=cron-apt state=latest
  tags: cron-apt
     
- name: Ensure ntp is at the latest version
  apt: name=ntp state=latest
  tags: ntp

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntp state=started enabled=true
  tags: ntp

- name: Ensure tmux is at the latest version
  apt: pkg=tmux state=latest
  tags: tmux
